language: go
go:
- 1.12.x
services:
- docker
install:
- go get ./...
- go get github.com/mattn/goveralls
script:
- export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRABIS_BRANCH;
  fi`
- go test -v -covermode=count -coverprofile=coverage.out ./...
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN"
after_success:
- CGO_ENABLED="0" GOARCH="amd64" GOOS="linux" go build -a -o ./dist/gauth-server cmd/server/*.go
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- export REPO=globbie/gauth
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "devel"
  ; fi`
- echo $REPO:$TAG
- docker build -f Dockerfile -t $REPO:$TAG .
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $REPO ; fi
before_deploy:
  - git config --local user.name "travis-ci"
  - git config --local user.email "info@globbie.com"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_TOKEN@github.com/globbie/gauth --tags
deploy:
  provider: releases
  name: "$GIT_TAG"
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  file: dist/gauth-server
  on:
    tags: false
    repo: globbie/gauth
    branch: master
notifications:
  slack:
    secure: yc+4ay2MNwX2mhg8w7T6Nzdt3E90+jCx3uok46s2gTVWhmjGbotf7KlWisn5cMwRCpjeeWQ7gw3951daA1ru2WEhvYhyKg1JA16aIGQJqY2BHQ2xwy6Blt9a2fhEPO+UfLkyc3POEJKAXqmOq5NqWyxAqQrM8l0bPiU1WaX0vupjBABG+49arzilfgA6bHAiKGsL2CMpR/iJ8sDe6RwLk+O1Dv0VqGI55uLmYEisy8Tf2O3x3muigXtkOiGi7L2lUyw13yydVjmmC3sRbTGXni0JJmPPYqMgI9M9SpfLDzBH6GZjMO95H+jrv39hKfx0uIUnI1e51muOfzgL4k5VmjYl8biZ5SSDaB2GrUQG4fR940S8ifIMqqm9RMaPEjtLWDthKKiZaQvtw8/2D04p89uh0CzO2UwdHy70IQJ4acgQayu3MSo3KZlYh6zO1AgnlqTQnEkNk50D/DhKWr+oQlAcoQqcfyHxi4cZmC3RGS9aUQzHjkgH8oWEoizIKJH+7mFD7ncBYsDR+3P2qd+GklLNcl+f2xMKKz0xEWg0E1DnyRgLeBohQODuiAoHSiDZOigMfDphZYW8IK5ybRTnx3nBIquV6nHm1eN/P2eWvV+oqLzivaNTsc8j4My1+g8h2vdUK9VRhK4y6aj8yp1OqHqkAeBG7IHGCTibei2g6NU=
env:
  global:
    secure: s2RAE9c+Xw7V/Ru9D/8iS7YdY6dZGpTiaz8cHcD7UTKarwrkhCN56Qa4PuEObdzdbUCSVzAtYbSrroJrnQplfMMI3n8DQ8Bw6qrnXbQ5CqyScGMhRtEdJAc3fwKN/t7QlxZJmqUT8wzmCD3b7io2ba69QNiALFt/RstBfZz5mockbLw811FEF3WXwC59/woeXXNDPGPnxcxwmh4TRxksNgs3AedTR7V8pnGwYkjETndIKM54a7IULTxamYqFSR1kuI7oO9T65fz1tM39wSQhPQoU+UlY5LREUDf33RzF4zFwdJpBYiGCW/KvY4BCgZiNsDGtwq7mfwBI9XHVZ0adJ053t3go5TDF8zeXlAC9WShp5JC8CvLeIIww7//R6lfvyoUUHWvEWDoYHVU9TOC5x5K0+li5cxtq/wJ93JmDmPzFuHKdCRZgxWrPq75P2eYXQXNiufokodouZgA9KMDsI+EMbcE1vNWVz+/liluKW7VdEQR1CLWUdY52P2s+F2yNkG7kjQad3KTT2QnCqjlBSVPNB16zpEjtx2BJ3MNCVmY/m3IzL/UrOVWklmmIq1jVs5KT80PAjXMAUgSQiJly8WhSO96KfN9XDkRblxyDmV8lwzRr4+2aqNLs0hYb0ris3V2PJFoSvzSrzPbmr7e1ReaRb3eoGQBcg+9HtiUepu4=
